<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <NuGetAuditSuppress>https://github.com/advisories/GHSA-6c8g-7p36-r338</NuGetAuditSuppress>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.8.0" />
    <PackageReference Include="SharpCompress" Version="0.47.4" />
    <PackageReference Include="Snappier" Version="1.3.1" />
    <ProjectReference Include="..\No2SQL.Utils\No2SQL.Utils.csproj" />
    <ProjectReference Include="..\No2SQL.Core\No2SQL.Core.csproj" />
  </ItemGroup>
</Project>
